var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":68,"id":396,"methods":[{"el":28,"sc":3,"sl":19},{"el":35,"sc":3,"sl":30},{"el":42,"sc":3,"sl":37},{"el":49,"sc":3,"sl":44},{"el":61,"sc":3,"sl":51},{"el":67,"sc":3,"sl":63}],"name":"ExcelMarshallerTest","sl":15}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":30}],"name":"testSimpleMembers","pass":true,"statements":[{"sl":32},{"sl":33},{"sl":34}]},"test_1":{"methods":[{"sl":37}],"name":"testEnum","pass":true,"statements":[{"sl":39},{"sl":40},{"sl":41}]},"test_11":{"methods":[{"sl":51}],"name":"testMemberWithMultiValue","pass":true,"statements":[{"sl":53},{"sl":54},{"sl":55},{"sl":56},{"sl":57},{"sl":58},{"sl":59},{"sl":60}]},"test_13":{"methods":[{"sl":63}],"name":"testMemberWithSimpleValue","pass":true,"statements":[{"sl":65},{"sl":66}]},"test_2":{"methods":[{"sl":30}],"name":"testSimpleMembers","pass":true,"statements":[{"sl":32},{"sl":33},{"sl":34}]},"test_4":{"methods":[{"sl":44}],"name":"testBeanMemberWithoutReference","pass":true,"statements":[{"sl":46},{"sl":47},{"sl":48}]},"test_6":{"methods":[{"sl":44}],"name":"testBeanMemberWithoutReference","pass":true,"statements":[{"sl":46},{"sl":47},{"sl":48}]},"test_7":{"methods":[{"sl":63}],"name":"testMemberWithSimpleValue","pass":true,"statements":[{"sl":65},{"sl":66}]},"test_8":{"methods":[{"sl":51}],"name":"testMemberWithMultiValue","pass":true,"statements":[{"sl":53},{"sl":54},{"sl":55},{"sl":56},{"sl":57},{"sl":58},{"sl":59},{"sl":60}]},"test_9":{"methods":[{"sl":37}],"name":"testEnum","pass":true,"statements":[{"sl":39},{"sl":40},{"sl":41}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [0, 2], [], [0, 2], [0, 2], [0, 2], [], [], [1, 9], [], [1, 9], [1, 9], [1, 9], [], [], [4, 6], [], [4, 6], [4, 6], [4, 6], [], [], [11, 8], [], [11, 8], [11, 8], [11, 8], [11, 8], [11, 8], [11, 8], [11, 8], [11, 8], [], [], [13, 7], [], [13, 7], [13, 7], [], []]
